name: Build Executable for Multiple Platforms

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ${{ matrix.os }}  # Runs the job for each OS defined in the matrix

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Define platforms (Ubuntu, Windows, macOS)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed facial_recognition.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable-${{ matrix.os }}  # Appending platform name to artifact
          path: dist/